### ISSUE TITLE
Little Busters! English Edition compatibility

### ISSUE THREAD

**Issue by RazoRTR** [RikuKH3/prot_tblpak#1]
The same file format (probably in a different way) was used in LB! EE too, albeit the game was made with a customized engine (LUCA Engine) made by Prototype. 
I've tried your tool on the .pak files of LB! EE but it always gives me this error (The file could not be located). I thought it was because my locale wasn't set to Japan, but it's still the same even though I set it to Japan:

![image](https://user-images.githubusercontent.com/4212660/32375532-a84f0324-c0aa-11e7-969a-3fc26a94a011.png)

The folder that the files are located in looks like this.
![image](https://user-images.githubusercontent.com/4212660/32375603-ee8cfcc4-c0aa-11e7-8c08-6d43d4d90573.png)

Yeah, it's running on a different engine, but it's still made by Prototype so there could be some similarities I hope. I'm wondering if you could add support for LB! EE. I'm uploading some files that I think that will be useful to you in your investigation. Thanks for your time!

[Little Busters! English Edition.zip](https://github.com/RikuKH3/prot_tblpak/files/1441179/Little.Busters.English.Edition.zip)

**Comment by RikuKH3** [comment]
This is completely different format... Looks much more simpler, but I won't add support for it.

**Comment by RazoRTR** [comment]
I see, thanks for digging up.

**Comment by RazoRTR** [comment]
Do you have any plans for making a tool for this format by any chance? I'm sure it'll be gold in the modding community. Just wondering.
(Also since I'm translating Little Busters' inferior version on Reallive engine, it'd be a huge advantage to adapt my translation onto the Steam version ^^" )

**Comment by AEBus** [comment]
>This is completely different format... Looks much more simpler, but I won't add support for it.

Жаль, очень хотелось бы получить утилиту по перепаковке
