### ISSUE TITLE
Any ideas about the *.dat file after extracting in psv Air

### ISSUE THREAD

**Issue by YuriSizuku** [RikuKH3/prot_tblpak#3]
Thank you for your tool, it works very well.

I use this tool in psv Air, a game by prototype company.
But I have no idea about the *.dat file.

For example, in psvcg file, 0033_1340700.dat whose size is 1373500 bytes,
and it's magic number is 02 01 20 00.

I guess it is a picture, but I don't know the compressing method or encryption.

**Comment by RikuKH3** [comment]
I'm not sharing anymore, sorry. Too tired of people using my code in their projects without even mentioning me.
